version: "3.5"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
        - 27017:27017
    network_mode: host
        
  app:
    image: spring-boot-docker-demo:latest
    ports:
    - 8080:8080
    network_mode: host